dist: bionic

sudo: required

language: python

python:
  - "3.7"

install:
  - python --version
  - pwd
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
#  - mkdir ~/.cloudmesh
#  - cp cloudmesh/etc/cloudmesh.yaml ~/.cloudmesh

script:
  - pytest -v tests/test_stopwatch.py
  - pytest -v tests/test_strdb.py
  - pytest -v tests/test_tables.py
  - pytest -v tests/test_flatdict.py
  - pytest -v tests/test_printer.py
  - pytest -v tests/test_shell.py
  - pytest -v --capture=no tests/test_stopwatch.py

# remove the verbose test as it does not work in python 2.7
#  - pytest -v tests/test_verbose.py
